### ISSUE TITLE
git clone hanging

### ISSUE THREAD

**Issue by magano** [tad-lispy/npm-git-install#4] opened 2016-03-11 18:10 UTC
For the last days I've been trying to use this package on a specific project but I'm facing an odd problem, the process blocks when it starts cloning the dependency and it hangs forever without any additional log.
This specific project works on other machines.

I'm using node 5.7.1, npm 3.6.0, git 2.6.4, OSX 10.11.3 on a Mac Pro Early 2015 if that helps in something.

I already tried to reinstall node, git and I also created a new user to test this with no success.

Is anyone facing the same problem? Any help is welcome, thank you.

**Comment by tad-lispy** [comment] 2016-03-11 22:26
Yesterday I've published new version to npm with updated `nodegit` dependency. Can you confirm the problem is still there with the new version?

**Comment by magano** [comment] 2016-03-11 23:24
I noticed that and I updated to the last version hoping it could work for me but it didn't.
Thanks for the quick reply, I will keep trying, I guess it is something with my computer, I'll try to figure out what.

**Comment by tad-lispy** [comment] 2016-03-12 11:10
Please share your findings. You may try `--verbose` option to pinpoint the issue.

**Comment by tad-lispy** [comment] 2016-03-12 11:13
Also consider if it's not a network related problems. Sometimes access to git servers is broken on some networks. Closing this issue for now, but can reopen if more info is provided.

**Closed as completed by tad-lispy** 2016-03-12 11:13 UTC
