### ISSUE TITLE
npm install succeeds but no temp directory is created for built package

### ISSUE THREAD

**Issue by JonathanSoper** [tad-lispy/npm-git-install#25] opened 2017-08-03 17:02 UTC
Hey, this is a great package, it works for me up to a certain point.  

I have a forked package from github, hosted under my own github account.  I made sure node and npm were updated and followed the instructions for npm-git-install.  It installed correctlyfrom my github to the point that the directory is created in node_modules, and it points to a temp directory.  however the temp directory doesn't exist.  I've done a --verbose install and it succeeds, but when I follow up with npm ls I get this output for that package:

├── UNMET DEPENDENCY package-name@file:../../../../../var/folders/df/gcycn6hj1w79lhy2r2575hrr0000gn/T/npm-git-11773-5388-j0u7av.tzkgfogvi

I'm guessing this might have something to do with permissions on my machine, but not sure.  I wanted to ask if you've ever come across this.  I'm using a mac, and it looks like the folder listed in the --verbose output, under /Users/myname/.npm is never created...

Any help or advice is appreciated. :)

**Comment by ginamako** [comment] 2017-12-11 14:36
I have the same issue. A solution would be highly appreciated.

**Comment by tad-lispy** [comment] 2017-12-11 16:10
Hello @BaseNineStudios and @ginamako.

Thank you for reporting. I'm sorry that I did not respond sooner. It's been a tense time for me on personal and professional grounds.

Regarding the issue, this may be related to #26. Could you please check and see if you have this kind of `../../../tmp` entry in your `package.json`?

**Comment by tad-lispy** [comment] 2024-02-15 09:40
Hey! Thanks for engaging with my project. It's been a while and I'm pretty sure the issue is not relevant to any of you (see https://github.com/npm/npm/issues/3055#issuecomment-304698029). Please let me know otherwise. Closing.

**Closed as completed** 2024-02-15 09:40 UTC
